// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.19.4
// source: filecenter.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type File struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int64  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Type       string `protobuf:"bytes,3,opt,name=Type,proto3" json:"Type,omitempty"`
	Path       string `protobuf:"bytes,4,opt,name=Path,proto3" json:"Path,omitempty"`
	Size       string `protobuf:"bytes,5,opt,name=Size,proto3" json:"Size,omitempty"`
	ShareLink  string `protobuf:"bytes,6,opt,name=ShareLink,proto3" json:"ShareLink,omitempty"`
	ModifyTime int64  `protobuf:"varint,7,opt,name=ModifyTime,proto3" json:"ModifyTime,omitempty"`
}

func (x *File) Reset() {
	*x = File{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filecenter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_filecenter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_filecenter_proto_rawDescGZIP(), []int{0}
}

func (x *File) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *File) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *File) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *File) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *File) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *File) GetShareLink() string {
	if x != nil {
		return x.ShareLink
	}
	return ""
}

func (x *File) GetModifyTime() int64 {
	if x != nil {
		return x.ModifyTime
	}
	return 0
}

type FileUploadReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Type       string `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`
	FileSize   int64  `protobuf:"varint,3,opt,name=FileSize,proto3" json:"FileSize,omitempty"`
	SourcePath string `protobuf:"bytes,4,opt,name=SourcePath,proto3" json:"SourcePath,omitempty"`
	Size       int64  `protobuf:"varint,5,opt,name=Size,proto3" json:"Size,omitempty"`
	Routines   int64  `protobuf:"varint,6,opt,name=Routines,proto3" json:"Routines,omitempty"`
}

func (x *FileUploadReq) Reset() {
	*x = FileUploadReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filecenter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileUploadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadReq) ProtoMessage() {}

func (x *FileUploadReq) ProtoReflect() protoreflect.Message {
	mi := &file_filecenter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadReq.ProtoReflect.Descriptor instead.
func (*FileUploadReq) Descriptor() ([]byte, []int) {
	return file_filecenter_proto_rawDescGZIP(), []int{1}
}

func (x *FileUploadReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileUploadReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FileUploadReq) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *FileUploadReq) GetSourcePath() string {
	if x != nil {
		return x.SourcePath
	}
	return ""
}

func (x *FileUploadReq) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileUploadReq) GetRoutines() int64 {
	if x != nil {
		return x.Routines
	}
	return 0
}

type FileUploadResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FileUploadResp) Reset() {
	*x = FileUploadResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filecenter_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileUploadResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadResp) ProtoMessage() {}

func (x *FileUploadResp) ProtoReflect() protoreflect.Message {
	mi := &file_filecenter_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadResp.ProtoReflect.Descriptor instead.
func (*FileUploadResp) Descriptor() ([]byte, []int) {
	return file_filecenter_proto_rawDescGZIP(), []int{2}
}

type FileDownloadReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Type string `protobuf:"bytes,3,opt,name=Type,proto3" json:"Type,omitempty"`
}

func (x *FileDownloadReq) Reset() {
	*x = FileDownloadReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filecenter_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileDownloadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDownloadReq) ProtoMessage() {}

func (x *FileDownloadReq) ProtoReflect() protoreflect.Message {
	mi := &file_filecenter_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDownloadReq.ProtoReflect.Descriptor instead.
func (*FileDownloadReq) Descriptor() ([]byte, []int) {
	return file_filecenter_proto_rawDescGZIP(), []int{3}
}

func (x *FileDownloadReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FileDownloadReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileDownloadReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type FileDownloadResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FileDownloadResp) Reset() {
	*x = FileDownloadResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filecenter_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileDownloadResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDownloadResp) ProtoMessage() {}

func (x *FileDownloadResp) ProtoReflect() protoreflect.Message {
	mi := &file_filecenter_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDownloadResp.ProtoReflect.Descriptor instead.
func (*FileDownloadResp) Descriptor() ([]byte, []int) {
	return file_filecenter_proto_rawDescGZIP(), []int{4}
}

type FileListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Page int64 `protobuf:"varint,2,opt,name=Page,proto3" json:"Page,omitempty"`
	Size int64 `protobuf:"varint,3,opt,name=Size,proto3" json:"Size,omitempty"`
}

func (x *FileListReq) Reset() {
	*x = FileListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filecenter_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileListReq) ProtoMessage() {}

func (x *FileListReq) ProtoReflect() protoreflect.Message {
	mi := &file_filecenter_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileListReq.ProtoReflect.Descriptor instead.
func (*FileListReq) Descriptor() ([]byte, []int) {
	return file_filecenter_proto_rawDescGZIP(), []int{5}
}

func (x *FileListReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FileListReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FileListReq) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type FileListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List  []*File `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
	Count int64   `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
}

func (x *FileListResp) Reset() {
	*x = FileListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filecenter_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileListResp) ProtoMessage() {}

func (x *FileListResp) ProtoReflect() protoreflect.Message {
	mi := &file_filecenter_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileListResp.ProtoReflect.Descriptor instead.
func (*FileListResp) Descriptor() ([]byte, []int) {
	return file_filecenter_proto_rawDescGZIP(), []int{6}
}

func (x *FileListResp) GetList() []*File {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *FileListResp) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type FileNameUpdateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Mame string `protobuf:"bytes,2,opt,name=Mame,proto3" json:"Mame,omitempty"`
}

func (x *FileNameUpdateReq) Reset() {
	*x = FileNameUpdateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filecenter_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileNameUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileNameUpdateReq) ProtoMessage() {}

func (x *FileNameUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_filecenter_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileNameUpdateReq.ProtoReflect.Descriptor instead.
func (*FileNameUpdateReq) Descriptor() ([]byte, []int) {
	return file_filecenter_proto_rawDescGZIP(), []int{7}
}

func (x *FileNameUpdateReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FileNameUpdateReq) GetMame() string {
	if x != nil {
		return x.Mame
	}
	return ""
}

type FileNameUpdateResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FileNameUpdateResp) Reset() {
	*x = FileNameUpdateResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filecenter_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileNameUpdateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileNameUpdateResp) ProtoMessage() {}

func (x *FileNameUpdateResp) ProtoReflect() protoreflect.Message {
	mi := &file_filecenter_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileNameUpdateResp.ProtoReflect.Descriptor instead.
func (*FileNameUpdateResp) Descriptor() ([]byte, []int) {
	return file_filecenter_proto_rawDescGZIP(), []int{8}
}

type FileCreateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ParentId int64  `protobuf:"varint,1,opt,name=ParentId,proto3" json:"ParentId,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *FileCreateReq) Reset() {
	*x = FileCreateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filecenter_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileCreateReq) ProtoMessage() {}

func (x *FileCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_filecenter_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileCreateReq.ProtoReflect.Descriptor instead.
func (*FileCreateReq) Descriptor() ([]byte, []int) {
	return file_filecenter_proto_rawDescGZIP(), []int{9}
}

func (x *FileCreateReq) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *FileCreateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type FileCreateResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FileCreateResp) Reset() {
	*x = FileCreateResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filecenter_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileCreateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileCreateResp) ProtoMessage() {}

func (x *FileCreateResp) ProtoReflect() protoreflect.Message {
	mi := &file_filecenter_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileCreateResp.ProtoReflect.Descriptor instead.
func (*FileCreateResp) Descriptor() ([]byte, []int) {
	return file_filecenter_proto_rawDescGZIP(), []int{10}
}

type FileDeletionReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *FileDeletionReq) Reset() {
	*x = FileDeletionReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filecenter_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileDeletionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDeletionReq) ProtoMessage() {}

func (x *FileDeletionReq) ProtoReflect() protoreflect.Message {
	mi := &file_filecenter_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDeletionReq.ProtoReflect.Descriptor instead.
func (*FileDeletionReq) Descriptor() ([]byte, []int) {
	return file_filecenter_proto_rawDescGZIP(), []int{11}
}

func (x *FileDeletionReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type FileDeletionResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FileDeletionResp) Reset() {
	*x = FileDeletionResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filecenter_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileDeletionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDeletionResp) ProtoMessage() {}

func (x *FileDeletionResp) ProtoReflect() protoreflect.Message {
	mi := &file_filecenter_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDeletionResp.ProtoReflect.Descriptor instead.
func (*FileDeletionResp) Descriptor() ([]byte, []int) {
	return file_filecenter_proto_rawDescGZIP(), []int{12}
}

type FileMoveReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LastParentId int64 `protobuf:"varint,1,opt,name=LastParentId,proto3" json:"LastParentId,omitempty"`
	PreParentId  int64 `protobuf:"varint,2,opt,name=PreParentId,proto3" json:"PreParentId,omitempty"`
	Id           int64 `protobuf:"varint,3,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *FileMoveReq) Reset() {
	*x = FileMoveReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filecenter_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileMoveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMoveReq) ProtoMessage() {}

func (x *FileMoveReq) ProtoReflect() protoreflect.Message {
	mi := &file_filecenter_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMoveReq.ProtoReflect.Descriptor instead.
func (*FileMoveReq) Descriptor() ([]byte, []int) {
	return file_filecenter_proto_rawDescGZIP(), []int{13}
}

func (x *FileMoveReq) GetLastParentId() int64 {
	if x != nil {
		return x.LastParentId
	}
	return 0
}

func (x *FileMoveReq) GetPreParentId() int64 {
	if x != nil {
		return x.PreParentId
	}
	return 0
}

func (x *FileMoveReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type FileMoveResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FileMoveResp) Reset() {
	*x = FileMoveResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filecenter_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileMoveResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMoveResp) ProtoMessage() {}

func (x *FileMoveResp) ProtoReflect() protoreflect.Message {
	mi := &file_filecenter_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMoveResp.ProtoReflect.Descriptor instead.
func (*FileMoveResp) Descriptor() ([]byte, []int) {
	return file_filecenter_proto_rawDescGZIP(), []int{14}
}

type FileShareReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *FileShareReq) Reset() {
	*x = FileShareReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filecenter_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileShareReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileShareReq) ProtoMessage() {}

func (x *FileShareReq) ProtoReflect() protoreflect.Message {
	mi := &file_filecenter_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileShareReq.ProtoReflect.Descriptor instead.
func (*FileShareReq) Descriptor() ([]byte, []int) {
	return file_filecenter_proto_rawDescGZIP(), []int{15}
}

func (x *FileShareReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type FileShareResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShareLink string `protobuf:"bytes,1,opt,name=ShareLink,proto3" json:"ShareLink,omitempty"`
}

func (x *FileShareResp) Reset() {
	*x = FileShareResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filecenter_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileShareResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileShareResp) ProtoMessage() {}

func (x *FileShareResp) ProtoReflect() protoreflect.Message {
	mi := &file_filecenter_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileShareResp.ProtoReflect.Descriptor instead.
func (*FileShareResp) Descriptor() ([]byte, []int) {
	return file_filecenter_proto_rawDescGZIP(), []int{16}
}

func (x *FileShareResp) GetShareLink() string {
	if x != nil {
		return x.ShareLink
	}
	return ""
}

type FileShareSaveReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ParentId  int64  `protobuf:"varint,1,opt,name=ParentId,proto3" json:"ParentId,omitempty"`
	ShareLink string `protobuf:"bytes,2,opt,name=ShareLink,proto3" json:"ShareLink,omitempty"`
	Name      string `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *FileShareSaveReq) Reset() {
	*x = FileShareSaveReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filecenter_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileShareSaveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileShareSaveReq) ProtoMessage() {}

func (x *FileShareSaveReq) ProtoReflect() protoreflect.Message {
	mi := &file_filecenter_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileShareSaveReq.ProtoReflect.Descriptor instead.
func (*FileShareSaveReq) Descriptor() ([]byte, []int) {
	return file_filecenter_proto_rawDescGZIP(), []int{17}
}

func (x *FileShareSaveReq) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *FileShareSaveReq) GetShareLink() string {
	if x != nil {
		return x.ShareLink
	}
	return ""
}

func (x *FileShareSaveReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type FileShareSaveResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *FileShareSaveResp) Reset() {
	*x = FileShareSaveResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filecenter_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileShareSaveResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileShareSaveResp) ProtoMessage() {}

func (x *FileShareSaveResp) ProtoReflect() protoreflect.Message {
	mi := &file_filecenter_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileShareSaveResp.ProtoReflect.Descriptor instead.
func (*FileShareSaveResp) Descriptor() ([]byte, []int) {
	return file_filecenter_proto_rawDescGZIP(), []int{18}
}

func (x *FileShareSaveResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type FileDetailsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *FileDetailsReq) Reset() {
	*x = FileDetailsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filecenter_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileDetailsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDetailsReq) ProtoMessage() {}

func (x *FileDetailsReq) ProtoReflect() protoreflect.Message {
	mi := &file_filecenter_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDetailsReq.ProtoReflect.Descriptor instead.
func (*FileDetailsReq) Descriptor() ([]byte, []int) {
	return file_filecenter_proto_rawDescGZIP(), []int{19}
}

func (x *FileDetailsReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type FileDetailsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Type string `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`
	Path string `protobuf:"bytes,3,opt,name=Path,proto3" json:"Path,omitempty"`
	Size string `protobuf:"bytes,4,opt,name=Size,proto3" json:"Size,omitempty"`
	Time string `protobuf:"bytes,5,opt,name=Time,proto3" json:"Time,omitempty"`
}

func (x *FileDetailsResp) Reset() {
	*x = FileDetailsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filecenter_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileDetailsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDetailsResp) ProtoMessage() {}

func (x *FileDetailsResp) ProtoReflect() protoreflect.Message {
	mi := &file_filecenter_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDetailsResp.ProtoReflect.Descriptor instead.
func (*FileDetailsResp) Descriptor() ([]byte, []int) {
	return file_filecenter_proto_rawDescGZIP(), []int{20}
}

func (x *FileDetailsResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileDetailsResp) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FileDetailsResp) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileDetailsResp) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *FileDetailsResp) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

var File_filecenter_proto protoreflect.FileDescriptor

var file_filecenter_proto_rawDesc = []byte{
	0x0a, 0x10, 0x66, 0x69, 0x6c, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0xa4, 0x01, 0x0a, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61, 0x74, 0x68, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x50, 0x61, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x53,
	0x69, 0x7a, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x53, 0x68, 0x61, 0x72, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x53, 0x68, 0x61, 0x72, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x1e, 0x0a,
	0x0a, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0a, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x22, 0xa3, 0x01,
	0x0a, 0x0d, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x12,
	0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x53,
	0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x53,
	0x69, 0x7a, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x50, 0x61, 0x74,
	0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x50,
	0x61, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x6f, 0x75, 0x74, 0x69,
	0x6e, 0x65, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x52, 0x6f, 0x75, 0x74, 0x69,
	0x6e, 0x65, 0x73, 0x22, 0x10, 0x0a, 0x0e, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x22, 0x49, 0x0a, 0x0f, 0x46, 0x69, 0x6c, 0x65, 0x44, 0x6f, 0x77,
	0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65,
	0x22, 0x12, 0x0a, 0x10, 0x46, 0x69, 0x6c, 0x65, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x22, 0x45, 0x0a, 0x0b, 0x46, 0x69, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x50, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x42, 0x0a, 0x0c, 0x46,
	0x69, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1c, 0x0a, 0x04, 0x4c,
	0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x46,
	0x69, 0x6c, 0x65, 0x52, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22,
	0x37, 0x0a, 0x11, 0x46, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4d, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x4d, 0x61, 0x6d, 0x65, 0x22, 0x14, 0x0a, 0x12, 0x46, 0x69, 0x6c, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x3f,
	0x0a, 0x0d, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12,
	0x1a, 0x0a, 0x08, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x22,
	0x10, 0x0a, 0x0e, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x21, 0x0a, 0x0f, 0x46, 0x69, 0x6c, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x49, 0x64, 0x22, 0x12, 0x0a, 0x10, 0x46, 0x69, 0x6c, 0x65, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x22, 0x63, 0x0a, 0x0b, 0x46, 0x69, 0x6c, 0x65,
	0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x12, 0x22, 0x0a, 0x0c, 0x4c, 0x61, 0x73, 0x74, 0x50,
	0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x4c,
	0x61, 0x73, 0x74, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x50,
	0x72, 0x65, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0b, 0x50, 0x72, 0x65, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x22, 0x0e, 0x0a,
	0x0c, 0x46, 0x69, 0x6c, 0x65, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x1e, 0x0a,
	0x0c, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x68, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x22, 0x2d, 0x0a,
	0x0d, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x68, 0x61, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1c,
	0x0a, 0x09, 0x53, 0x68, 0x61, 0x72, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x53, 0x68, 0x61, 0x72, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x22, 0x60, 0x0a, 0x10,
	0x46, 0x69, 0x6c, 0x65, 0x53, 0x68, 0x61, 0x72, 0x65, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71,
	0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09,
	0x53, 0x68, 0x61, 0x72, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x53, 0x68, 0x61, 0x72, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x23,
	0x0a, 0x11, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x68, 0x61, 0x72, 0x65, 0x53, 0x61, 0x76, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x49, 0x64, 0x22, 0x20, 0x0a, 0x0e, 0x46, 0x69, 0x6c, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x73, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x49, 0x64, 0x22, 0x75, 0x0a, 0x0f, 0x46, 0x69, 0x6c, 0x65, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x50, 0x61, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x50, 0x61, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x69, 0x6d, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x32, 0xb3, 0x04, 0x0a,
	0x0a, 0x66, 0x69, 0x6c, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x33, 0x0a, 0x0a, 0x46,
	0x69, 0x6c, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x46,
	0x69, 0x6c, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x70,
	0x62, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x39, 0x0a, 0x0c, 0x46, 0x69, 0x6c, 0x65, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64,
	0x12, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f,
	0x61, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x44,
	0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2d, 0x0a, 0x08, 0x46,
	0x69, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x6c,
	0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x69,
	0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3f, 0x0a, 0x0e, 0x46, 0x69,
	0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x15, 0x2e, 0x70,
	0x62, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x33, 0x0a, 0x0a, 0x46,
	0x69, 0x6c, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x46,
	0x69, 0x6c, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x70,
	0x62, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x39, 0x0a, 0x0c, 0x46, 0x69, 0x6c, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2d, 0x0a, 0x08, 0x46,
	0x69, 0x6c, 0x65, 0x4d, 0x6f, 0x76, 0x65, 0x12, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x6c,
	0x65, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x69,
	0x6c, 0x65, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x30, 0x0a, 0x09, 0x46, 0x69,
	0x6c, 0x65, 0x53, 0x68, 0x61, 0x72, 0x65, 0x12, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x6c,
	0x65, 0x53, 0x68, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x46,
	0x69, 0x6c, 0x65, 0x53, 0x68, 0x61, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3c, 0x0a, 0x0d,
	0x46, 0x69, 0x6c, 0x65, 0x53, 0x68, 0x61, 0x72, 0x65, 0x53, 0x61, 0x76, 0x65, 0x12, 0x14, 0x2e,
	0x70, 0x62, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x68, 0x61, 0x72, 0x65, 0x53, 0x61, 0x76, 0x65,
	0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x68, 0x61,
	0x72, 0x65, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x36, 0x0a, 0x0b, 0x46, 0x69,
	0x6c, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x46,
	0x69, 0x6c, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e,
	0x70, 0x62, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_filecenter_proto_rawDescOnce sync.Once
	file_filecenter_proto_rawDescData = file_filecenter_proto_rawDesc
)

func file_filecenter_proto_rawDescGZIP() []byte {
	file_filecenter_proto_rawDescOnce.Do(func() {
		file_filecenter_proto_rawDescData = protoimpl.X.CompressGZIP(file_filecenter_proto_rawDescData)
	})
	return file_filecenter_proto_rawDescData
}

var file_filecenter_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_filecenter_proto_goTypes = []interface{}{
	(*File)(nil),               // 0: pb.File
	(*FileUploadReq)(nil),      // 1: pb.FileUploadReq
	(*FileUploadResp)(nil),     // 2: pb.FileUploadResp
	(*FileDownloadReq)(nil),    // 3: pb.FileDownloadReq
	(*FileDownloadResp)(nil),   // 4: pb.FileDownloadResp
	(*FileListReq)(nil),        // 5: pb.FileListReq
	(*FileListResp)(nil),       // 6: pb.FileListResp
	(*FileNameUpdateReq)(nil),  // 7: pb.FileNameUpdateReq
	(*FileNameUpdateResp)(nil), // 8: pb.FileNameUpdateResp
	(*FileCreateReq)(nil),      // 9: pb.FileCreateReq
	(*FileCreateResp)(nil),     // 10: pb.FileCreateResp
	(*FileDeletionReq)(nil),    // 11: pb.FileDeletionReq
	(*FileDeletionResp)(nil),   // 12: pb.FileDeletionResp
	(*FileMoveReq)(nil),        // 13: pb.FileMoveReq
	(*FileMoveResp)(nil),       // 14: pb.FileMoveResp
	(*FileShareReq)(nil),       // 15: pb.FileShareReq
	(*FileShareResp)(nil),      // 16: pb.FileShareResp
	(*FileShareSaveReq)(nil),   // 17: pb.FileShareSaveReq
	(*FileShareSaveResp)(nil),  // 18: pb.FileShareSaveResp
	(*FileDetailsReq)(nil),     // 19: pb.FileDetailsReq
	(*FileDetailsResp)(nil),    // 20: pb.FileDetailsResp
}
var file_filecenter_proto_depIdxs = []int32{
	0,  // 0: pb.FileListResp.List:type_name -> pb.File
	1,  // 1: pb.filecenter.FileUpload:input_type -> pb.FileUploadReq
	3,  // 2: pb.filecenter.FileDownload:input_type -> pb.FileDownloadReq
	5,  // 3: pb.filecenter.FileList:input_type -> pb.FileListReq
	7,  // 4: pb.filecenter.FileNameUpdate:input_type -> pb.FileNameUpdateReq
	9,  // 5: pb.filecenter.FileCreate:input_type -> pb.FileCreateReq
	11, // 6: pb.filecenter.FileDeletion:input_type -> pb.FileDeletionReq
	13, // 7: pb.filecenter.FileMove:input_type -> pb.FileMoveReq
	15, // 8: pb.filecenter.FileShare:input_type -> pb.FileShareReq
	17, // 9: pb.filecenter.FileShareSave:input_type -> pb.FileShareSaveReq
	19, // 10: pb.filecenter.FileDetails:input_type -> pb.FileDetailsReq
	2,  // 11: pb.filecenter.FileUpload:output_type -> pb.FileUploadResp
	4,  // 12: pb.filecenter.FileDownload:output_type -> pb.FileDownloadResp
	6,  // 13: pb.filecenter.FileList:output_type -> pb.FileListResp
	8,  // 14: pb.filecenter.FileNameUpdate:output_type -> pb.FileNameUpdateResp
	10, // 15: pb.filecenter.FileCreate:output_type -> pb.FileCreateResp
	12, // 16: pb.filecenter.FileDeletion:output_type -> pb.FileDeletionResp
	14, // 17: pb.filecenter.FileMove:output_type -> pb.FileMoveResp
	16, // 18: pb.filecenter.FileShare:output_type -> pb.FileShareResp
	18, // 19: pb.filecenter.FileShareSave:output_type -> pb.FileShareSaveResp
	20, // 20: pb.filecenter.FileDetails:output_type -> pb.FileDetailsResp
	11, // [11:21] is the sub-list for method output_type
	1,  // [1:11] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_filecenter_proto_init() }
func file_filecenter_proto_init() {
	if File_filecenter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_filecenter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*File); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_filecenter_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileUploadReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_filecenter_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileUploadResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_filecenter_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileDownloadReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_filecenter_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileDownloadResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_filecenter_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_filecenter_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_filecenter_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileNameUpdateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_filecenter_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileNameUpdateResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_filecenter_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileCreateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_filecenter_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileCreateResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_filecenter_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileDeletionReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_filecenter_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileDeletionResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_filecenter_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileMoveReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_filecenter_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileMoveResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_filecenter_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileShareReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_filecenter_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileShareResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_filecenter_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileShareSaveReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_filecenter_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileShareSaveResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_filecenter_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileDetailsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_filecenter_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileDetailsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_filecenter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_filecenter_proto_goTypes,
		DependencyIndexes: file_filecenter_proto_depIdxs,
		MessageInfos:      file_filecenter_proto_msgTypes,
	}.Build()
	File_filecenter_proto = out.File
	file_filecenter_proto_rawDesc = nil
	file_filecenter_proto_goTypes = nil
	file_filecenter_proto_depIdxs = nil
}
