// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	user "CloudMind/app/usercenter/cmd/api/internal/handler/user"
	"CloudMind/app/usercenter/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/Register",
				Handler: user.RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/AccountLogin",
				Handler: user.AcloginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/QqLogin",
				Handler: user.QqloginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/WxLogin",
				Handler: user.WxloginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/EmailLogin",
				Handler: user.EmailloginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/SendEmail",
				Handler: user.SendemailHandler(serverCtx),
			},
		},
		rest.WithPrefix("/usercenter/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/user/GetInfo",
				Handler: user.GetinfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/UpdatePassword",
				Handler: user.UpdatepasswordHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/UpdateEmail",
				Handler: user.UpdateemailHandler(serverCtx),
			},
		},
		rest.WithPrefix("/usercenter/v1"),
	)
}
