// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	login "CloudMind/app/usercenter/cmd/api/internal/handler/login"
	"CloudMind/app/usercenter/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login/Register",
				Handler: login.RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login/EmailLogin",
				Handler: login.EmailLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login/QqLogin",
				Handler: login.QqloginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login/WxLogin",
				Handler: login.WxloginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login/SendEmail",
				Handler: login.SendEmailHandler(serverCtx),
			},
		},
		rest.WithPrefix("/usercenter/v1"),
	)
}
