// Code generated by goctl. DO NOT EDIT.
// Source: file.proto

package server

import (
	"context"

	"CloudMind/app/filecenter/cmd/rpc/internal/logic"
	"CloudMind/app/filecenter/cmd/rpc/internal/svc"
	"CloudMind/app/filecenter/cmd/rpc/pb"
)

type FilecenterServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedFilecenterServer
}

func NewFilecenterServer(svcCtx *svc.ServiceContext) *FilecenterServer {
	return &FilecenterServer{
		svcCtx: svcCtx,
	}
}

func (s *FilecenterServer) FileUpload(ctx context.Context, in *pb.FileUploadReq) (*pb.FileUploadResp, error) {
	l := logic.NewFileUploadLogic(ctx, s.svcCtx)
	return l.FileUpload(in)
}

func (s *FilecenterServer) FileDownload(ctx context.Context, in *pb.FileDownloadReq) (*pb.FileDownloadResp, error) {
	l := logic.NewFileDownloadLogic(ctx, s.svcCtx)
	return l.FileDownload(in)
}

func (s *FilecenterServer) FileList(ctx context.Context, in *pb.FileListReq) (*pb.FileListResp, error) {
	l := logic.NewFileListLogic(ctx, s.svcCtx)
	return l.FileList(in)
}

func (s *FilecenterServer) FileNameUpdate(ctx context.Context, in *pb.FileNameUpdateReq) (*pb.FileNameUpdateResp, error) {
	l := logic.NewFileNameUpdateLogic(ctx, s.svcCtx)
	return l.FileNameUpdate(in)
}

func (s *FilecenterServer) FileCreate(ctx context.Context, in *pb.FileCreateReq) (*pb.FileCreateResp, error) {
	l := logic.NewFileCreateLogic(ctx, s.svcCtx)
	return l.FileCreate(in)
}

func (s *FilecenterServer) FileDeletion(ctx context.Context, in *pb.FileDeletionReq) (*pb.FileDeletionResp, error) {
	l := logic.NewFileDeletionLogic(ctx, s.svcCtx)
	return l.FileDeletion(in)
}

func (s *FilecenterServer) FileMove(ctx context.Context, in *pb.FileMoveReq) (*pb.FileMoveResp, error) {
	l := logic.NewFileMoveLogic(ctx, s.svcCtx)
	return l.FileMove(in)
}

func (s *FilecenterServer) FileShare(ctx context.Context, in *pb.FileShareReq) (*pb.FileShareResp, error) {
	l := logic.NewFileShareLogic(ctx, s.svcCtx)
	return l.FileShare(in)
}

func (s *FilecenterServer) FileShareSave(ctx context.Context, in *pb.FileShareSaveReq) (*pb.FileShareSaveResp, error) {
	l := logic.NewFileShareSaveLogic(ctx, s.svcCtx)
	return l.FileShareSave(in)
}

func (s *FilecenterServer) FileDetails(ctx context.Context, in *pb.FileDetailsReq) (*pb.FileDetailsResp, error) {
	l := logic.NewFileDetailsLogic(ctx, s.svcCtx)
	return l.FileDetails(in)
}
