// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	search "CloudMind/app/es/cmd/api/internal/handler/search"
	"CloudMind/app/es/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/search/SearchForFiles",
				Handler: search.SearchForFilesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/search/SearchForPosts",
				Handler: search.SearchForPostsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/search/SearchForFilesByUserId",
				Handler: search.SearchForFilesByUserIdHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/search/SearchForPostsByUserId",
				Handler: search.SearchForPostsByUserIdHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/search/SearchForFilesRank",
				Handler: search.SearchForFilesRankHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/search/SearchForPostsRank",
				Handler: search.SearchForPostsRankHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/es/v1"),
	)
}
