// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.19.4
// source: es.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 文件信息
// 文件名， 文件id
type File struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title string `protobuf:"bytes,1,opt,name=Title,proto3" json:"Title"`
	Id    string `protobuf:"bytes,2,opt,name=Id,proto3" json:"Id"`
}

func (x *File) Reset() {
	*x = File{}
	if protoimpl.UnsafeEnabled {
		mi := &file_es_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_es_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_es_proto_rawDescGZIP(), []int{0}
}

func (x *File) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *File) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// 帖子信息
// 帖子标题， 帖子内容， 帖子id
type Post struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title   string `protobuf:"bytes,1,opt,name=Title,proto3" json:"Title"`
	Content string `protobuf:"bytes,2,opt,name=Content,proto3" json:"Content"`
	Id      string `protobuf:"bytes,3,opt,name=Id,proto3" json:"Id"`
}

func (x *Post) Reset() {
	*x = Post{}
	if protoimpl.UnsafeEnabled {
		mi := &file_es_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Post) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Post) ProtoMessage() {}

func (x *Post) ProtoReflect() protoreflect.Message {
	mi := &file_es_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Post.ProtoReflect.Descriptor instead.
func (*Post) Descriptor() ([]byte, []int) {
	return file_es_proto_rawDescGZIP(), []int{1}
}

func (x *Post) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Post) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Post) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// 查找文件
// Content： 具体内容
type SearchForFilesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content"`
}

func (x *SearchForFilesReq) Reset() {
	*x = SearchForFilesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_es_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchForFilesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchForFilesReq) ProtoMessage() {}

func (x *SearchForFilesReq) ProtoReflect() protoreflect.Message {
	mi := &file_es_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchForFilesReq.ProtoReflect.Descriptor instead.
func (*SearchForFilesReq) Descriptor() ([]byte, []int) {
	return file_es_proto_rawDescGZIP(), []int{2}
}

func (x *SearchForFilesReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type SearchForFilesResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Files []*File `protobuf:"bytes,1,rep,name=Files,proto3" json:"Files"`
	Error string  `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error"`
}

func (x *SearchForFilesResp) Reset() {
	*x = SearchForFilesResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_es_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchForFilesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchForFilesResp) ProtoMessage() {}

func (x *SearchForFilesResp) ProtoReflect() protoreflect.Message {
	mi := &file_es_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchForFilesResp.ProtoReflect.Descriptor instead.
func (*SearchForFilesResp) Descriptor() ([]byte, []int) {
	return file_es_proto_rawDescGZIP(), []int{3}
}

func (x *SearchForFilesResp) GetFiles() []*File {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *SearchForFilesResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 查找帖子
// Content： 具体内容
type SearchForPostsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content"`
}

func (x *SearchForPostsReq) Reset() {
	*x = SearchForPostsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_es_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchForPostsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchForPostsReq) ProtoMessage() {}

func (x *SearchForPostsReq) ProtoReflect() protoreflect.Message {
	mi := &file_es_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchForPostsReq.ProtoReflect.Descriptor instead.
func (*SearchForPostsReq) Descriptor() ([]byte, []int) {
	return file_es_proto_rawDescGZIP(), []int{4}
}

func (x *SearchForPostsReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type SearchForPostsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Posts []*Post `protobuf:"bytes,1,rep,name=Posts,proto3" json:"Posts"`
	Error string  `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error"`
}

func (x *SearchForPostsResp) Reset() {
	*x = SearchForPostsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_es_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchForPostsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchForPostsResp) ProtoMessage() {}

func (x *SearchForPostsResp) ProtoReflect() protoreflect.Message {
	mi := &file_es_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchForPostsResp.ProtoReflect.Descriptor instead.
func (*SearchForPostsResp) Descriptor() ([]byte, []int) {
	return file_es_proto_rawDescGZIP(), []int{5}
}

func (x *SearchForPostsResp) GetPosts() []*Post {
	if x != nil {
		return x.Posts
	}
	return nil
}

func (x *SearchForPostsResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 下载/点赞/收藏量 文件排行
type SearchForFileRankReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ranking   int64  `protobuf:"varint,1,opt,name=Ranking,proto3" json:"Ranking"`
	TypeMount string `protobuf:"bytes,2,opt,name=TypeMount,proto3" json:"TypeMount"`
}

func (x *SearchForFileRankReq) Reset() {
	*x = SearchForFileRankReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_es_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchForFileRankReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchForFileRankReq) ProtoMessage() {}

func (x *SearchForFileRankReq) ProtoReflect() protoreflect.Message {
	mi := &file_es_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchForFileRankReq.ProtoReflect.Descriptor instead.
func (*SearchForFileRankReq) Descriptor() ([]byte, []int) {
	return file_es_proto_rawDescGZIP(), []int{6}
}

func (x *SearchForFileRankReq) GetRanking() int64 {
	if x != nil {
		return x.Ranking
	}
	return 0
}

func (x *SearchForFileRankReq) GetTypeMount() string {
	if x != nil {
		return x.TypeMount
	}
	return ""
}

type SearchForFileRankResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Files []*File `protobuf:"bytes,1,rep,name=Files,proto3" json:"Files"`
	Error string  `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error"`
}

func (x *SearchForFileRankResp) Reset() {
	*x = SearchForFileRankResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_es_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchForFileRankResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchForFileRankResp) ProtoMessage() {}

func (x *SearchForFileRankResp) ProtoReflect() protoreflect.Message {
	mi := &file_es_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchForFileRankResp.ProtoReflect.Descriptor instead.
func (*SearchForFileRankResp) Descriptor() ([]byte, []int) {
	return file_es_proto_rawDescGZIP(), []int{7}
}

func (x *SearchForFileRankResp) GetFiles() []*File {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *SearchForFileRankResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 总/月/周/日榜 浏览/点赞/收藏量 帖子排行
type SearchForPostsRankReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ranking   int64  `protobuf:"varint,1,opt,name=Ranking,proto3" json:"Ranking"`
	TypeMount string `protobuf:"bytes,2,opt,name=TypeMount,proto3" json:"TypeMount"`
}

func (x *SearchForPostsRankReq) Reset() {
	*x = SearchForPostsRankReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_es_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchForPostsRankReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchForPostsRankReq) ProtoMessage() {}

func (x *SearchForPostsRankReq) ProtoReflect() protoreflect.Message {
	mi := &file_es_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchForPostsRankReq.ProtoReflect.Descriptor instead.
func (*SearchForPostsRankReq) Descriptor() ([]byte, []int) {
	return file_es_proto_rawDescGZIP(), []int{8}
}

func (x *SearchForPostsRankReq) GetRanking() int64 {
	if x != nil {
		return x.Ranking
	}
	return 0
}

func (x *SearchForPostsRankReq) GetTypeMount() string {
	if x != nil {
		return x.TypeMount
	}
	return ""
}

type SearchForPostsRankResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Posts []*Post `protobuf:"bytes,1,rep,name=Posts,proto3" json:"Posts"`
	Error string  `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error"`
}

func (x *SearchForPostsRankResp) Reset() {
	*x = SearchForPostsRankResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_es_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchForPostsRankResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchForPostsRankResp) ProtoMessage() {}

func (x *SearchForPostsRankResp) ProtoReflect() protoreflect.Message {
	mi := &file_es_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchForPostsRankResp.ProtoReflect.Descriptor instead.
func (*SearchForPostsRankResp) Descriptor() ([]byte, []int) {
	return file_es_proto_rawDescGZIP(), []int{9}
}

func (x *SearchForPostsRankResp) GetPosts() []*Post {
	if x != nil {
		return x.Posts
	}
	return nil
}

func (x *SearchForPostsRankResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 用户id
// 查询下载/点赞/收藏过的文件
type SearchForFilesByIdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id"`
	Type string `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type"`
}

func (x *SearchForFilesByIdReq) Reset() {
	*x = SearchForFilesByIdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_es_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchForFilesByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchForFilesByIdReq) ProtoMessage() {}

func (x *SearchForFilesByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_es_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchForFilesByIdReq.ProtoReflect.Descriptor instead.
func (*SearchForFilesByIdReq) Descriptor() ([]byte, []int) {
	return file_es_proto_rawDescGZIP(), []int{10}
}

func (x *SearchForFilesByIdReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SearchForFilesByIdReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type SearchForFilesByIdResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Files []*File `protobuf:"bytes,1,rep,name=Files,proto3" json:"Files"`
	Error string  `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error"`
}

func (x *SearchForFilesByIdResp) Reset() {
	*x = SearchForFilesByIdResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_es_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchForFilesByIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchForFilesByIdResp) ProtoMessage() {}

func (x *SearchForFilesByIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_es_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchForFilesByIdResp.ProtoReflect.Descriptor instead.
func (*SearchForFilesByIdResp) Descriptor() ([]byte, []int) {
	return file_es_proto_rawDescGZIP(), []int{11}
}

func (x *SearchForFilesByIdResp) GetFiles() []*File {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *SearchForFilesByIdResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 用户id
// 查询点赞/收藏过的帖子
type SearchForPostsByIdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id"`
	Type string `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type"`
}

func (x *SearchForPostsByIdReq) Reset() {
	*x = SearchForPostsByIdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_es_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchForPostsByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchForPostsByIdReq) ProtoMessage() {}

func (x *SearchForPostsByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_es_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchForPostsByIdReq.ProtoReflect.Descriptor instead.
func (*SearchForPostsByIdReq) Descriptor() ([]byte, []int) {
	return file_es_proto_rawDescGZIP(), []int{12}
}

func (x *SearchForPostsByIdReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SearchForPostsByIdReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type SearchForPostsByIdResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Posts []*Post `protobuf:"bytes,1,rep,name=Posts,proto3" json:"Posts"`
	Error string  `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error"`
}

func (x *SearchForPostsByIdResp) Reset() {
	*x = SearchForPostsByIdResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_es_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchForPostsByIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchForPostsByIdResp) ProtoMessage() {}

func (x *SearchForPostsByIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_es_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchForPostsByIdResp.ProtoReflect.Descriptor instead.
func (*SearchForPostsByIdResp) Descriptor() ([]byte, []int) {
	return file_es_proto_rawDescGZIP(), []int{13}
}

func (x *SearchForPostsByIdResp) GetPosts() []*Post {
	if x != nil {
		return x.Posts
	}
	return nil
}

func (x *SearchForPostsByIdResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 修改文件标题
type UpdateFilesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	File *File `protobuf:"bytes,1,opt,name=File,proto3" json:"File"`
}

func (x *UpdateFilesReq) Reset() {
	*x = UpdateFilesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_es_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateFilesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFilesReq) ProtoMessage() {}

func (x *UpdateFilesReq) ProtoReflect() protoreflect.Message {
	mi := &file_es_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFilesReq.ProtoReflect.Descriptor instead.
func (*UpdateFilesReq) Descriptor() ([]byte, []int) {
	return file_es_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateFilesReq) GetFile() *File {
	if x != nil {
		return x.File
	}
	return nil
}

type UpdateFilesResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error"`
}

func (x *UpdateFilesResp) Reset() {
	*x = UpdateFilesResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_es_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateFilesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFilesResp) ProtoMessage() {}

func (x *UpdateFilesResp) ProtoReflect() protoreflect.Message {
	mi := &file_es_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFilesResp.ProtoReflect.Descriptor instead.
func (*UpdateFilesResp) Descriptor() ([]byte, []int) {
	return file_es_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateFilesResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 修改帖子标题/内容
type UpdatePostsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Post *Post `protobuf:"bytes,1,opt,name=Post,proto3" json:"Post"`
}

func (x *UpdatePostsReq) Reset() {
	*x = UpdatePostsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_es_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePostsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePostsReq) ProtoMessage() {}

func (x *UpdatePostsReq) ProtoReflect() protoreflect.Message {
	mi := &file_es_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePostsReq.ProtoReflect.Descriptor instead.
func (*UpdatePostsReq) Descriptor() ([]byte, []int) {
	return file_es_proto_rawDescGZIP(), []int{16}
}

func (x *UpdatePostsReq) GetPost() *Post {
	if x != nil {
		return x.Post
	}
	return nil
}

type UpdatePostsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error"`
}

func (x *UpdatePostsResp) Reset() {
	*x = UpdatePostsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_es_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePostsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePostsResp) ProtoMessage() {}

func (x *UpdatePostsResp) ProtoReflect() protoreflect.Message {
	mi := &file_es_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePostsResp.ProtoReflect.Descriptor instead.
func (*UpdatePostsResp) Descriptor() ([]byte, []int) {
	return file_es_proto_rawDescGZIP(), []int{17}
}

func (x *UpdatePostsResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type InsertFileReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	File      *File  `protobuf:"bytes,1,opt,name=File,proto3" json:"File"`
	UserId    int64  `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId"`
	TypeMount string `protobuf:"bytes,3,opt,name=TypeMount,proto3" json:"TypeMount"`
}

func (x *InsertFileReq) Reset() {
	*x = InsertFileReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_es_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertFileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertFileReq) ProtoMessage() {}

func (x *InsertFileReq) ProtoReflect() protoreflect.Message {
	mi := &file_es_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertFileReq.ProtoReflect.Descriptor instead.
func (*InsertFileReq) Descriptor() ([]byte, []int) {
	return file_es_proto_rawDescGZIP(), []int{18}
}

func (x *InsertFileReq) GetFile() *File {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *InsertFileReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *InsertFileReq) GetTypeMount() string {
	if x != nil {
		return x.TypeMount
	}
	return ""
}

type InsertFileResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error"`
}

func (x *InsertFileResp) Reset() {
	*x = InsertFileResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_es_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertFileResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertFileResp) ProtoMessage() {}

func (x *InsertFileResp) ProtoReflect() protoreflect.Message {
	mi := &file_es_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertFileResp.ProtoReflect.Descriptor instead.
func (*InsertFileResp) Descriptor() ([]byte, []int) {
	return file_es_proto_rawDescGZIP(), []int{19}
}

func (x *InsertFileResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type InsertPostReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Post      *Post  `protobuf:"bytes,1,opt,name=Post,proto3" json:"Post"`
	UserId    int64  `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId"`
	TypeMount string `protobuf:"bytes,3,opt,name=TypeMount,proto3" json:"TypeMount"`
}

func (x *InsertPostReq) Reset() {
	*x = InsertPostReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_es_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertPostReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertPostReq) ProtoMessage() {}

func (x *InsertPostReq) ProtoReflect() protoreflect.Message {
	mi := &file_es_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertPostReq.ProtoReflect.Descriptor instead.
func (*InsertPostReq) Descriptor() ([]byte, []int) {
	return file_es_proto_rawDescGZIP(), []int{20}
}

func (x *InsertPostReq) GetPost() *Post {
	if x != nil {
		return x.Post
	}
	return nil
}

func (x *InsertPostReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *InsertPostReq) GetTypeMount() string {
	if x != nil {
		return x.TypeMount
	}
	return ""
}

type InsertPostResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error"`
}

func (x *InsertPostResp) Reset() {
	*x = InsertPostResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_es_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertPostResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertPostResp) ProtoMessage() {}

func (x *InsertPostResp) ProtoReflect() protoreflect.Message {
	mi := &file_es_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertPostResp.ProtoReflect.Descriptor instead.
func (*InsertPostResp) Descriptor() ([]byte, []int) {
	return file_es_proto_rawDescGZIP(), []int{21}
}

func (x *InsertPostResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_es_proto protoreflect.FileDescriptor

var file_es_proto_rawDesc = []byte{
	0x0a, 0x08, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x2c,
	0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x22, 0x46, 0x0a, 0x04,
	0x70, 0x6f, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x49, 0x64, 0x22, 0x2d, 0x0a, 0x11, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x46, 0x6f,
	0x72, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x22, 0x4a, 0x0a, 0x12, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x46, 0x6f, 0x72,
	0x46, 0x69, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1e, 0x0a, 0x05, 0x46, 0x69, 0x6c,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x66, 0x69,
	0x6c, 0x65, 0x52, 0x05, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x22,
	0x2d, 0x0a, 0x11, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x46, 0x6f, 0x72, 0x50, 0x6f, 0x73, 0x74,
	0x73, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x4a,
	0x0a, 0x12, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x46, 0x6f, 0x72, 0x50, 0x6f, 0x73, 0x74, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x1e, 0x0a, 0x05, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x52, 0x05, 0x50,
	0x6f, 0x73, 0x74, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x4e, 0x0a, 0x14, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x46, 0x6f, 0x72, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x61, 0x6e, 0x6b, 0x52,
	0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x12, 0x1c, 0x0a, 0x09,
	0x54, 0x79, 0x70, 0x65, 0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x54, 0x79, 0x70, 0x65, 0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x4d, 0x0a, 0x15, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x46, 0x6f, 0x72, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x61, 0x6e, 0x6b, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x1e, 0x0a, 0x05, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x05, 0x46, 0x69,
	0x6c, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x4f, 0x0a, 0x15, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x46, 0x6f, 0x72, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x52, 0x61, 0x6e, 0x6b, 0x52,
	0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x12, 0x1c, 0x0a, 0x09,
	0x54, 0x79, 0x70, 0x65, 0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x54, 0x79, 0x70, 0x65, 0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x4e, 0x0a, 0x16, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x46, 0x6f, 0x72, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x52, 0x61, 0x6e, 0x6b,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x1e, 0x0a, 0x05, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x52, 0x05, 0x50,
	0x6f, 0x73, 0x74, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x3b, 0x0a, 0x15, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x46, 0x6f, 0x72, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x42, 0x79, 0x49, 0x64,
	0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x22, 0x4e, 0x0a, 0x16, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x46, 0x6f, 0x72, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x1e, 0x0a, 0x05, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x05, 0x46, 0x69, 0x6c, 0x65,
	0x73, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x3b, 0x0a, 0x15, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x46, 0x6f, 0x72, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x54, 0x79, 0x70, 0x65, 0x22, 0x4e, 0x0a, 0x16, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x46, 0x6f,
	0x72, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1e,
	0x0a, 0x05, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e,
	0x70, 0x62, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x52, 0x05, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x22, 0x2e, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x69,
	0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x04,
	0x46, 0x69, 0x6c, 0x65, 0x22, 0x27, 0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x69,
	0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x2e, 0x0a,
	0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x12,
	0x1c, 0x0a, 0x04, 0x50, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e,
	0x70, 0x62, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x52, 0x04, 0x50, 0x6f, 0x73, 0x74, 0x22, 0x27, 0x0a,
	0x0f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x14, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x63, 0x0a, 0x0d, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74,
	0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x52,
	0x04, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a,
	0x09, 0x54, 0x79, 0x70, 0x65, 0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x54, 0x79, 0x70, 0x65, 0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x26, 0x0a, 0x0e, 0x49,
	0x6e, 0x73, 0x65, 0x72, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14, 0x0a,
	0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x22, 0x63, 0x0a, 0x0d, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x50, 0x6f, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x04, 0x50, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x52, 0x04, 0x50, 0x6f,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x79,
	0x70, 0x65, 0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x54,
	0x79, 0x70, 0x65, 0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x26, 0x0a, 0x0e, 0x49, 0x6e, 0x73, 0x65,
	0x72, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x32, 0x91, 0x05, 0x0a, 0x02, 0x65, 0x73, 0x12, 0x3f, 0x0a, 0x0e, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x46, 0x6f, 0x72, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x46, 0x6f, 0x72, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71,
	0x1a, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x46, 0x6f, 0x72, 0x46,
	0x69, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3f, 0x0a, 0x0e, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x46, 0x6f, 0x72, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x12, 0x15, 0x2e, 0x70, 0x62, 0x2e,
	0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x46, 0x6f, 0x72, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x52, 0x65,
	0x71, 0x1a, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x46, 0x6f, 0x72,
	0x50, 0x6f, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x48, 0x0a, 0x11, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x46, 0x6f, 0x72, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x61, 0x6e, 0x6b, 0x12, 0x18,
	0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x46, 0x6f, 0x72, 0x46, 0x69, 0x6c,
	0x65, 0x52, 0x61, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x46, 0x6f, 0x72, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x61, 0x6e, 0x6b, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x4b, 0x0a, 0x12, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x46, 0x6f, 0x72,
	0x50, 0x6f, 0x73, 0x74, 0x73, 0x52, 0x61, 0x6e, 0x6b, 0x12, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x46, 0x6f, 0x72, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x52, 0x61, 0x6e,
	0x6b, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x46, 0x6f, 0x72, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x52, 0x61, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x4b, 0x0a, 0x12, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x46, 0x6f, 0x72, 0x46, 0x69, 0x6c,
	0x65, 0x73, 0x42, 0x79, 0x49, 0x64, 0x12, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x46, 0x6f, 0x72, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65,
	0x71, 0x1a, 0x1a, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x46, 0x6f, 0x72,
	0x46, 0x69, 0x6c, 0x65, 0x73, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x4b, 0x0a,
	0x12, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x46, 0x6f, 0x72, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x42,
	0x79, 0x49, 0x64, 0x12, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x46,
	0x6f, 0x72, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x1a,
	0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x46, 0x6f, 0x72, 0x50, 0x6f, 0x73,
	0x74, 0x73, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x36, 0x0a, 0x0b, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e,
	0x70, 0x62, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x36, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74,
	0x73, 0x12, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x73,
	0x74, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x33, 0x0a, 0x0a, 0x49, 0x6e,
	0x73, 0x65, 0x72, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x6e,
	0x73, 0x65, 0x72, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x70, 0x62,
	0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x33, 0x0a, 0x0a, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x12, 0x11, 0x2e,
	0x70, 0x62, 0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x1a, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x50, 0x6f, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_es_proto_rawDescOnce sync.Once
	file_es_proto_rawDescData = file_es_proto_rawDesc
)

func file_es_proto_rawDescGZIP() []byte {
	file_es_proto_rawDescOnce.Do(func() {
		file_es_proto_rawDescData = protoimpl.X.CompressGZIP(file_es_proto_rawDescData)
	})
	return file_es_proto_rawDescData
}

var file_es_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_es_proto_goTypes = []interface{}{
	(*File)(nil),                   // 0: pb.file
	(*Post)(nil),                   // 1: pb.post
	(*SearchForFilesReq)(nil),      // 2: pb.SearchForFilesReq
	(*SearchForFilesResp)(nil),     // 3: pb.SearchForFilesResp
	(*SearchForPostsReq)(nil),      // 4: pb.SearchForPostsReq
	(*SearchForPostsResp)(nil),     // 5: pb.SearchForPostsResp
	(*SearchForFileRankReq)(nil),   // 6: pb.SearchForFileRankReq
	(*SearchForFileRankResp)(nil),  // 7: pb.SearchForFileRankResp
	(*SearchForPostsRankReq)(nil),  // 8: pb.SearchForPostsRankReq
	(*SearchForPostsRankResp)(nil), // 9: pb.SearchForPostsRankResp
	(*SearchForFilesByIdReq)(nil),  // 10: pb.SearchForFilesByIdReq
	(*SearchForFilesByIdResp)(nil), // 11: pb.SearchForFilesByIdResp
	(*SearchForPostsByIdReq)(nil),  // 12: pb.SearchForPostsByIdReq
	(*SearchForPostsByIdResp)(nil), // 13: pb.SearchForPostsByIdResp
	(*UpdateFilesReq)(nil),         // 14: pb.UpdateFilesReq
	(*UpdateFilesResp)(nil),        // 15: pb.UpdateFilesResp
	(*UpdatePostsReq)(nil),         // 16: pb.UpdatePostsReq
	(*UpdatePostsResp)(nil),        // 17: pb.UpdatePostsResp
	(*InsertFileReq)(nil),          // 18: pb.InsertFileReq
	(*InsertFileResp)(nil),         // 19: pb.InsertFileResp
	(*InsertPostReq)(nil),          // 20: pb.InsertPostReq
	(*InsertPostResp)(nil),         // 21: pb.InsertPostResp
}
var file_es_proto_depIdxs = []int32{
	0,  // 0: pb.SearchForFilesResp.Files:type_name -> pb.file
	1,  // 1: pb.SearchForPostsResp.Posts:type_name -> pb.post
	0,  // 2: pb.SearchForFileRankResp.Files:type_name -> pb.file
	1,  // 3: pb.SearchForPostsRankResp.Posts:type_name -> pb.post
	0,  // 4: pb.SearchForFilesByIdResp.Files:type_name -> pb.file
	1,  // 5: pb.SearchForPostsByIdResp.Posts:type_name -> pb.post
	0,  // 6: pb.UpdateFilesReq.File:type_name -> pb.file
	1,  // 7: pb.UpdatePostsReq.Post:type_name -> pb.post
	0,  // 8: pb.InsertFileReq.File:type_name -> pb.file
	1,  // 9: pb.InsertPostReq.Post:type_name -> pb.post
	2,  // 10: pb.es.SearchForFiles:input_type -> pb.SearchForFilesReq
	4,  // 11: pb.es.SearchForPosts:input_type -> pb.SearchForPostsReq
	6,  // 12: pb.es.SearchForFileRank:input_type -> pb.SearchForFileRankReq
	8,  // 13: pb.es.SearchForPostsRank:input_type -> pb.SearchForPostsRankReq
	10, // 14: pb.es.SearchForFilesById:input_type -> pb.SearchForFilesByIdReq
	12, // 15: pb.es.SearchForPostsById:input_type -> pb.SearchForPostsByIdReq
	14, // 16: pb.es.UpdateFiles:input_type -> pb.UpdateFilesReq
	16, // 17: pb.es.UpdatePosts:input_type -> pb.UpdatePostsReq
	18, // 18: pb.es.InsertFile:input_type -> pb.InsertFileReq
	20, // 19: pb.es.InsertPost:input_type -> pb.InsertPostReq
	3,  // 20: pb.es.SearchForFiles:output_type -> pb.SearchForFilesResp
	5,  // 21: pb.es.SearchForPosts:output_type -> pb.SearchForPostsResp
	7,  // 22: pb.es.SearchForFileRank:output_type -> pb.SearchForFileRankResp
	9,  // 23: pb.es.SearchForPostsRank:output_type -> pb.SearchForPostsRankResp
	11, // 24: pb.es.SearchForFilesById:output_type -> pb.SearchForFilesByIdResp
	13, // 25: pb.es.SearchForPostsById:output_type -> pb.SearchForPostsByIdResp
	15, // 26: pb.es.UpdateFiles:output_type -> pb.UpdateFilesResp
	17, // 27: pb.es.UpdatePosts:output_type -> pb.UpdatePostsResp
	19, // 28: pb.es.InsertFile:output_type -> pb.InsertFileResp
	21, // 29: pb.es.InsertPost:output_type -> pb.InsertPostResp
	20, // [20:30] is the sub-list for method output_type
	10, // [10:20] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_es_proto_init() }
func file_es_proto_init() {
	if File_es_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_es_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*File); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_es_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Post); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_es_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchForFilesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_es_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchForFilesResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_es_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchForPostsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_es_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchForPostsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_es_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchForFileRankReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_es_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchForFileRankResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_es_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchForPostsRankReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_es_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchForPostsRankResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_es_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchForFilesByIdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_es_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchForFilesByIdResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_es_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchForPostsByIdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_es_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchForPostsByIdResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_es_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateFilesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_es_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateFilesResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_es_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePostsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_es_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePostsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_es_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertFileReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_es_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertFileResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_es_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertPostReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_es_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertPostResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_es_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_es_proto_goTypes,
		DependencyIndexes: file_es_proto_depIdxs,
		MessageInfos:      file_es_proto_msgTypes,
	}.Build()
	File_es_proto = out.File
	file_es_proto_rawDesc = nil
	file_es_proto_goTypes = nil
	file_es_proto_depIdxs = nil
}
