// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"CloudMind/common/globalkey"
	"CloudMind/common/xerr"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userAuthFieldNames          = builder.RawFieldNames(&UserAuth{})
	userAuthRows                = strings.Join(userAuthFieldNames, ",")
	userAuthRowsExpectAutoSet   = strings.Join(stringx.Remove(userAuthFieldNames, "`account`", "`create_time`", "`update_time`"), ",")
	userAuthRowsWithPlaceHolder = strings.Join(stringx.Remove(userAuthFieldNames, "`account`", "`create_time`", "`update_time`"), "=?,") + "=?"

	cacheCloudMindUsercenterUserAuthAccountPrefix         = "cache:cloudMindUsercenter:userAuth:account:"
	cacheCloudMindUsercenterUserAuthAccountAuthTypePrefix = "cache:cloudMindUsercenter:userAuth:account:authType:"
	cacheCloudMindUsercenterUserAuthAuthTypeAuthKeyPrefix = "cache:cloudMindUsercenter:userAuth:authType:authKey:"
)

type (
	userAuthModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *UserAuth) (sql.Result, error)
		FindOne(ctx context.Context, account int64) (*UserAuth, error)
		FindOneByAccountAuthType(ctx context.Context, account int64, authType string) (*UserAuth, error)
		FindOneByAuthTypeAuthKey(ctx context.Context, authType string, authKey string) (*UserAuth, error)
		Update(ctx context.Context, session sqlx.Session, data *UserAuth) (sql.Result, error)
		UpdateWithVersion(ctx context.Context, session sqlx.Session, data *UserAuth) error
		Delete(ctx context.Context, session sqlx.Session, account int64) error
	}

	defaultUserAuthModel struct {
		sqlc.CachedConn
		table string
	}

	UserAuth struct {
		Account    int64     `db:"account"`
		CreateTime time.Time `db:"create_time"`
		UpdateTime time.Time `db:"update_time"`
		DeleteTime time.Time `db:"delete_time"`
		DelState   int64     `db:"del_state"`
		Version    int64     `db:"version"`   // 版本号
		AuthKey    string    `db:"auth_key"`  // 平台唯一id
		AuthType   string    `db:"auth_type"` // 平台类型
	}
)

func newUserAuthModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultUserAuthModel {
	return &defaultUserAuthModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`user_auth`",
	}
}

func (m *defaultUserAuthModel) Insert(ctx context.Context, session sqlx.Session, data *UserAuth) (sql.Result, error) {
	data.DeleteTime = time.Unix(0, 0)
	cloudMindUsercenterUserAuthAccountAuthTypeKey := fmt.Sprintf("%s%v:%v", cacheCloudMindUsercenterUserAuthAccountAuthTypePrefix, data.Account, data.AuthType)
	cloudMindUsercenterUserAuthAccountKey := fmt.Sprintf("%s%v", cacheCloudMindUsercenterUserAuthAccountPrefix, data.Account)
	cloudMindUsercenterUserAuthAuthTypeAuthKeyKey := fmt.Sprintf("%s%v:%v", cacheCloudMindUsercenterUserAuthAuthTypeAuthKeyPrefix, data.AuthType, data.AuthKey)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, userAuthRowsExpectAutoSet)
		if session != nil {
			return session.ExecCtx(ctx, query, data.DeleteTime, data.DelState, data.Version, data.AuthKey, data.AuthType)
		}
		return conn.ExecCtx(ctx, query, data.DeleteTime, data.DelState, data.Version, data.AuthKey, data.AuthType)
	}, cloudMindUsercenterUserAuthAccountAuthTypeKey, cloudMindUsercenterUserAuthAccountKey, cloudMindUsercenterUserAuthAuthTypeAuthKeyKey)
}

func (m *defaultUserAuthModel) FindOne(ctx context.Context, account int64) (*UserAuth, error) {
	cloudMindUsercenterUserAuthAccountKey := fmt.Sprintf("%s%v", cacheCloudMindUsercenterUserAuthAccountPrefix, account)
	var resp UserAuth
	err := m.QueryRowCtx(ctx, &resp, cloudMindUsercenterUserAuthAccountKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `account` = ? and del_state = ? limit 1", userAuthRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, account, globalkey.DelStateNo)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserAuthModel) FindOneByAccountAuthType(ctx context.Context, account int64, authType string) (*UserAuth, error) {
	cloudMindUsercenterUserAuthAccountAuthTypeKey := fmt.Sprintf("%s%v:%v", cacheCloudMindUsercenterUserAuthAccountAuthTypePrefix, account, authType)
	var resp UserAuth
	err := m.QueryRowIndexCtx(ctx, &resp, cloudMindUsercenterUserAuthAccountAuthTypeKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) (i interface{}, e error) {
		query := fmt.Sprintf("select %s from %s where `account` = ? and `auth_type` = ? and del_state = ? limit 1", userAuthRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, account, authType, globalkey.DelStateNo); err != nil {
			return nil, err
		}
		return resp.Account, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserAuthModel) FindOneByAuthTypeAuthKey(ctx context.Context, authType string, authKey string) (*UserAuth, error) {
	cloudMindUsercenterUserAuthAuthTypeAuthKeyKey := fmt.Sprintf("%s%v:%v", cacheCloudMindUsercenterUserAuthAuthTypeAuthKeyPrefix, authType, authKey)
	var resp UserAuth
	err := m.QueryRowIndexCtx(ctx, &resp, cloudMindUsercenterUserAuthAuthTypeAuthKeyKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) (i interface{}, e error) {
		query := fmt.Sprintf("select %s from %s where `auth_type` = ? and `auth_key` = ? and del_state = ? limit 1", userAuthRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, authType, authKey, globalkey.DelStateNo); err != nil {
			return nil, err
		}
		return resp.Account, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserAuthModel) Update(ctx context.Context, session sqlx.Session, data *UserAuth) (sql.Result, error) {
	cloudMindUsercenterUserAuthAccountAuthTypeKey := fmt.Sprintf("%s%v:%v", cacheCloudMindUsercenterUserAuthAccountAuthTypePrefix, data.Account, data.AuthType)
	cloudMindUsercenterUserAuthAccountKey := fmt.Sprintf("%s%v", cacheCloudMindUsercenterUserAuthAccountPrefix, data.Account)
	cloudMindUsercenterUserAuthAuthTypeAuthKeyKey := fmt.Sprintf("%s%v:%v", cacheCloudMindUsercenterUserAuthAuthTypeAuthKeyPrefix, data.AuthType, data.AuthKey)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `account` = ?", m.table, userAuthRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, data.DeleteTime, data.DelState, data.Version, data.AuthKey, data.AuthType, data.Account)
		}
		return conn.ExecCtx(ctx, query, data.DeleteTime, data.DelState, data.Version, data.AuthKey, data.AuthType, data.Account)
	}, cloudMindUsercenterUserAuthAccountAuthTypeKey, cloudMindUsercenterUserAuthAccountKey, cloudMindUsercenterUserAuthAuthTypeAuthKeyKey)
}

func (m *defaultUserAuthModel) UpdateWithVersion(ctx context.Context, session sqlx.Session, data *UserAuth) error {

	oldVersion := data.Version
	data.Version += 1

	var sqlResult sql.Result
	var err error

	cloudMindUsercenterUserAuthAccountAuthTypeKey := fmt.Sprintf("%s%v:%v", cacheCloudMindUsercenterUserAuthAccountAuthTypePrefix, data.Account, data.AuthType)
	cloudMindUsercenterUserAuthAccountKey := fmt.Sprintf("%s%v", cacheCloudMindUsercenterUserAuthAccountPrefix, data.Account)
	cloudMindUsercenterUserAuthAuthTypeAuthKeyKey := fmt.Sprintf("%s%v:%v", cacheCloudMindUsercenterUserAuthAuthTypeAuthKeyPrefix, data.AuthType, data.AuthKey)
	sqlResult, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `account` = ? and version = ? ", m.table, userAuthRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, data.DeleteTime, data.DelState, data.Version, data.AuthKey, data.AuthType, data.Account, oldVersion)
		}
		return conn.ExecCtx(ctx, query, data.DeleteTime, data.DelState, data.Version, data.AuthKey, data.AuthType, data.Account, oldVersion)
	}, cloudMindUsercenterUserAuthAccountAuthTypeKey, cloudMindUsercenterUserAuthAccountKey, cloudMindUsercenterUserAuthAuthTypeAuthKeyKey)
	if err != nil {
		return err
	}
	updateCount, err := sqlResult.RowsAffected()
	if err != nil {
		return err
	}
	if updateCount == 0 {
		return xerr.NewErrCode(xerr.DB_UPDATE_AFFECTED_ZERO_ERROR)
	}

	return nil
}

func (m *defaultUserAuthModel) Delete(ctx context.Context, session sqlx.Session, account int64) error {
	data, err := m.FindOne(ctx, account)
	if err != nil {
		return err
	}

	cloudMindUsercenterUserAuthAccountAuthTypeKey := fmt.Sprintf("%s%v:%v", cacheCloudMindUsercenterUserAuthAccountAuthTypePrefix, data.Account, data.AuthType)
	cloudMindUsercenterUserAuthAccountKey := fmt.Sprintf("%s%v", cacheCloudMindUsercenterUserAuthAccountPrefix, account)
	cloudMindUsercenterUserAuthAuthTypeAuthKeyKey := fmt.Sprintf("%s%v:%v", cacheCloudMindUsercenterUserAuthAuthTypeAuthKeyPrefix, data.AuthType, data.AuthKey)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `account` = ?", m.table)
		if session != nil {
			return session.ExecCtx(ctx, query, account)
		}
		return conn.ExecCtx(ctx, query, account)
	}, cloudMindUsercenterUserAuthAccountAuthTypeKey, cloudMindUsercenterUserAuthAccountKey, cloudMindUsercenterUserAuthAuthTypeAuthKeyKey)
	return err
}

func (m *defaultUserAuthModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheCloudMindUsercenterUserAuthAccountPrefix, primary)
}
func (m *defaultUserAuthModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `account` = ? and del_state = ? limit 1", userAuthRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary, globalkey.DelStateNo)
}

func (m *defaultUserAuthModel) tableName() string {
	return m.table
}
