// Code generated by goctl. DO NOT EDIT.
package types

type User struct {
	Account  int64  `json:"account"` // 账号
	PassWord string `json:"passWord"`
	NickName string `json:"nickName"`
	Email    string `json:"email"`
	Sex      string `json:"sex"`
	Name     string `json:"name"`
	IdCard   string `json:"idCard"`
}

type RegisterReq struct {
	NickName string `json:"nickName"`
	PassWord string `json:"passWord"`
	Sex      string `json:"sex"`
}

type RegisterResp struct {
	Account      string `json:"account"`
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type AccountLoginReq struct {
	Account  string `json:"account"`
	PassWord string `json:"passWord"`
}

type AccountLoginResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type GetInfoReq struct {
}

type GetInfoResp struct {
	UserInfo User `json:"userInfo"`
}

type QqLoginReq struct {
}

type QqLoginResp struct {
}

type WxLoginReq struct {
}

type WxLoginResp struct {
}

type EmailLoginReq struct {
}

type EmailLoginResp struct {
}

type SendEmailReq struct {
}

type SendEmailResp struct {
}

type UpdateEmailReq struct {
}

type UpdateEmailResp struct {
}

type UpdatePassWordReq struct {
}

type UpdatePassWordResp struct {
}
