// Code generated by goctl. DO NOT EDIT.
// Source: es.proto

package server

import (
	"context"

	"CloudMind/app/es/cmd/rpc/internal/logic"
	"CloudMind/app/es/cmd/rpc/internal/svc"
	"CloudMind/app/es/cmd/rpc/pb"
)

type EsServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedEsServer
}

func NewEsServer(svcCtx *svc.ServiceContext) *EsServer {
	return &EsServer{
		svcCtx: svcCtx,
	}
}

func (s *EsServer) SearchFor(ctx context.Context, in *pb.SearchForReq) (*pb.SearchForResp, error) {
	l := logic.NewSearchForLogic(ctx, s.svcCtx)
	return l.SearchFor(in)
}

func (s *EsServer) AddText(ctx context.Context, in *pb.AddTextReq) (*pb.AddTextResp, error) {
	l := logic.NewAddTextLogic(ctx, s.svcCtx)
	return l.AddText(in)
}
