// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	file "CloudMind/app/filecenter/cmd/api/internal/handler/file"
	"CloudMind/app/filecenter/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/file/fileUpload",
				Handler: file.FileuploadHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/file/fileDownload",
				Handler: file.FiledownloadHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/file/fileList",
				Handler: file.FilelistHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/file/fileNameUpdate",
				Handler: file.FilenameupdateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/file/fileCreate",
				Handler: file.FilecreateHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/file/fileDeletion",
				Handler: file.FiledeletionHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/file/fileMove",
				Handler: file.FilemoveHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/file/fileShare",
				Handler: file.FileshareHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/file/fileShareSave",
				Handler: file.FilesharesaveHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/file/fileDetails",
				Handler: file.FiledetailsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/filecenter/v1"),
	)
}
