// Code generated by goctl. DO NOT EDIT.
// Source: file.proto

package filecenter

import (
	"context"

	"CloudMind/app/fileservice/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	File               = pb.File
	FileCreateReq      = pb.FileCreateReq
	FileCreateResp     = pb.FileCreateResp
	FileDeletionReq    = pb.FileDeletionReq
	FileDeletionResp   = pb.FileDeletionResp
	FileDetailsReq     = pb.FileDetailsReq
	FileDetailsResp    = pb.FileDetailsResp
	FileDownloadReq    = pb.FileDownloadReq
	FileDownloadResp   = pb.FileDownloadResp
	FileListReq        = pb.FileListReq
	FileListResp       = pb.FileListResp
	FileMoveReq        = pb.FileMoveReq
	FileMoveResp       = pb.FileMoveResp
	FileNameUpdateReq  = pb.FileNameUpdateReq
	FileNameUpdateResp = pb.FileNameUpdateResp
	FileShareReq       = pb.FileShareReq
	FileShareResp      = pb.FileShareResp
	FileShareSaveReq   = pb.FileShareSaveReq
	FileShareSaveResp  = pb.FileShareSaveResp
	FileUploadReq      = pb.FileUploadReq
	FileUploadResp     = pb.FileUploadResp

	Filecenter interface {
		FileUpload(ctx context.Context, in *FileUploadReq, opts ...grpc.CallOption) (*FileUploadResp, error)
		FileDownload(ctx context.Context, in *FileDownloadReq, opts ...grpc.CallOption) (*FileDownloadResp, error)
		FileList(ctx context.Context, in *FileListReq, opts ...grpc.CallOption) (*FileListResp, error)
		FileNameUpdate(ctx context.Context, in *FileNameUpdateReq, opts ...grpc.CallOption) (*FileNameUpdateResp, error)
		FileCreate(ctx context.Context, in *FileCreateReq, opts ...grpc.CallOption) (*FileCreateResp, error)
		FileDeletion(ctx context.Context, in *FileDeletionReq, opts ...grpc.CallOption) (*FileDeletionResp, error)
		FileMove(ctx context.Context, in *FileMoveReq, opts ...grpc.CallOption) (*FileMoveResp, error)
		FileShare(ctx context.Context, in *FileShareReq, opts ...grpc.CallOption) (*FileShareResp, error)
		FileShareSave(ctx context.Context, in *FileShareSaveReq, opts ...grpc.CallOption) (*FileShareSaveResp, error)
		FileDetails(ctx context.Context, in *FileDetailsReq, opts ...grpc.CallOption) (*FileDetailsResp, error)
	}

	defaultFilecenter struct {
		cli zrpc.Client
	}
)

func NewFilecenter(cli zrpc.Client) Filecenter {
	return &defaultFilecenter{
		cli: cli,
	}
}

func (m *defaultFilecenter) FileUpload(ctx context.Context, in *FileUploadReq, opts ...grpc.CallOption) (*FileUploadResp, error) {
	client := pb.NewFilecenterClient(m.cli.Conn())
	return client.FileUpload(ctx, in, opts...)
}

func (m *defaultFilecenter) FileDownload(ctx context.Context, in *FileDownloadReq, opts ...grpc.CallOption) (*FileDownloadResp, error) {
	client := pb.NewFilecenterClient(m.cli.Conn())
	return client.FileDownload(ctx, in, opts...)
}

func (m *defaultFilecenter) FileList(ctx context.Context, in *FileListReq, opts ...grpc.CallOption) (*FileListResp, error) {
	client := pb.NewFilecenterClient(m.cli.Conn())
	return client.FileList(ctx, in, opts...)
}

func (m *defaultFilecenter) FileNameUpdate(ctx context.Context, in *FileNameUpdateReq, opts ...grpc.CallOption) (*FileNameUpdateResp, error) {
	client := pb.NewFilecenterClient(m.cli.Conn())
	return client.FileNameUpdate(ctx, in, opts...)
}

func (m *defaultFilecenter) FileCreate(ctx context.Context, in *FileCreateReq, opts ...grpc.CallOption) (*FileCreateResp, error) {
	client := pb.NewFilecenterClient(m.cli.Conn())
	return client.FileCreate(ctx, in, opts...)
}

func (m *defaultFilecenter) FileDeletion(ctx context.Context, in *FileDeletionReq, opts ...grpc.CallOption) (*FileDeletionResp, error) {
	client := pb.NewFilecenterClient(m.cli.Conn())
	return client.FileDeletion(ctx, in, opts...)
}

func (m *defaultFilecenter) FileMove(ctx context.Context, in *FileMoveReq, opts ...grpc.CallOption) (*FileMoveResp, error) {
	client := pb.NewFilecenterClient(m.cli.Conn())
	return client.FileMove(ctx, in, opts...)
}

func (m *defaultFilecenter) FileShare(ctx context.Context, in *FileShareReq, opts ...grpc.CallOption) (*FileShareResp, error) {
	client := pb.NewFilecenterClient(m.cli.Conn())
	return client.FileShare(ctx, in, opts...)
}

func (m *defaultFilecenter) FileShareSave(ctx context.Context, in *FileShareSaveReq, opts ...grpc.CallOption) (*FileShareSaveResp, error) {
	client := pb.NewFilecenterClient(m.cli.Conn())
	return client.FileShareSave(ctx, in, opts...)
}

func (m *defaultFilecenter) FileDetails(ctx context.Context, in *FileDetailsReq, opts ...grpc.CallOption) (*FileDetailsResp, error) {
	client := pb.NewFilecenterClient(m.cli.Conn())
	return client.FileDetails(ctx, in, opts...)
}
