// Code generated by goctl. DO NOT EDIT.
package types

type File struct {
	Title string `json:"title"`
	Id    string `json:"id"`
}

type Posts struct {
	Title   string `json:"title"`
	Content string `json:"content"`
	Id      string `json:"id"`
}

type SearchForFilesReq struct {
	Content string `json:"content"`
}

type SearchForFilesResp struct {
	Files []File `json:"files"`
	Error string `json:"error"`
}

type SearchForPostsReq struct {
	Content string `json:"content"`
}

type SearchForPostsResp struct {
	Posts []Posts `json:"posts"`
	Error string  `json:"error"`
}

type SearchForFilesByUserIdReq struct {
	UserId    int64  `json:"userId"`
	TypeMount string `json:"typeMount"`
}

type SearchForFilesByUserIdResp struct {
	Files []File `json:"files"`
	Error string `json:"error"`
}

type SearchForPostsByUserIdReq struct {
	UserId    int64  `json:"userId"`
	TypeMount string `json:"typeMount"`
}

type SearchForPostsByUserIdResp struct {
	Posts []Posts `json:"posts"`
	Error string  `json:"error"`
}

type SearchForFilesRankReq struct {
	Rank      int64  `json:"rank"`
	TypeMount string `json:"typeMount"`
}

type SearchForFilesRankResp struct {
	Files []File `json:"files"`
	Error string `json:"error"`
}

type SearchForPostsRankReq struct {
	Rank      int64  `json:"rank"`
	TypeMount string `json:"typeMount"`
}

type SearchForPostsRankResp struct {
	Posts []Posts `json:"posts"`
	Error string  `json:"error"`
}

type UpdateFilesReq struct {
	File File `json:"file"`
}

type UpdateFilesResp struct {
	Error string `json:"error"`
}

type UpdatePostsReq struct {
	Post Posts `json:"post"`
}

type UpdatePostsResp struct {
	Error string `json:"error"`
}
